/* Dati del viaggio in Polonia 4-11 agosto 2026.
   Estratti il 2026-08-02 da:
     - agenzia-viaggi/output/schedule-giorno-per-giorno.md (versione 2026-08-01)
     - knowledge/itinerario/playbook-risposte-mail.md (versione 2026-08-02)
   Dove i due file si contraddicono vince il PLAYBOOK (più recente).
   NESSUN codice di prenotazione qui dentro: stanno solo nel PDF offline. */

const VIAGGIO = {
  titolo: "Polonia 2026",
  sottotitolo: "4 - 11 agosto - 6 persone - 2 auto",
  aggiornato: "10 agosto 2026 (sera) - ultimo giorno rifatto + scheda Etna",

  giorni: [
    /* ---------------------------------------------------------------- G1 */
    {
      n: 1,
      meteo: { luogo: "Varsavia", lat: 52.23, lon: 21.01 },
      data: "2026-08-04",
      etichetta: "Martedì 4 agosto",
      titolo: "Volo, arrivo a Modlin, prima sera in Città Vecchia",
      base: "Varsavia",
      sveglia: "~6:00",
      carico: "medio",
      cappello: "Niente auto oggi né domani: si ritira giovedì. Ci si muove con transfer, metro e tram.",
      tappe: [
        { ora: "~6:00", titolo: "Sveglia, transfer per l'aeroporto di Catania",
          note: "Carte d'imbarco SOLO sull'app Ryanair: non si stampano più.", tipo: "riposo" },
        { ora: "09:05", fisso: true, titolo: "Volo Ryanair FR5441 - Catania > Varsavia Modlin",
          note: "2h45 di volo, atterra alle 11:50. Priorità + 2 bagagli a mano, zero stiva.", tipo: "fisso", mail: "https://app.notion.com/p/3b0bdffea7c781faa7e2fe1836fc9aee" },
        { ora: "11:50", titolo: "Atterraggio, sbarco, uscita",
          note: "Volo Schengen (niente passaporti) e zero bagagli in stiva: si esce veloci, fuori verso le 12:15.", tipo: "fisso" },
        { ora: "~12:15", titolo: "Transfer Modlin > ibis Styles Grzybowska 43",
          dove: "40 km - 57 min normale, fino a 1h22 col traffico peggiore",
          note: "Minivan privato Welcome Pickups (8 posti) già prenotato. L'autista monitora il volo. Cercare l'hotel per INDIRIZZO Grzybowska 43, mai per nome: a Varsavia ci sono tre ibis Styles.",
          vai: "https://www.google.com/maps/dir/?api=1&destination=ibis%20Styles%20Warszawa%20City%2C%20Grzybowska%2043%2C%2000-855%20Warszawa%2C%20Poland&travelmode=driving", modo: "driving", tipo: "spost", mail: "https://app.notion.com/p/3b0bdffea7c781faa7e2fe1836fc9aee" },
        { ora: "~13:15", titolo: "Arrivo hotel, deposito bagagli",
          dove: "ibis Styles, Grzybowska 43",
          note: "Camera disponibile dalle 15:00. Se non è pronta si lasciano le valigie e si esce lo stesso. Colazione e WiFi inclusi, già tutto pagato.", tipo: "spost", mail: "https://app.notion.com/p/3b0bdffea7c781faa7e2fe1836fc9aee" },
        { ora: "~13:45", titolo: "Pranzo leggero in zona hotel", dove: "Wola / Rondo ONZ",
          note: "Zona di uffici moderni, molti posti veloci e onesti attorno a Rondo ONZ (450 m).",
          vai: "https://www.google.com/maps/dir/?api=1&destination=Rondo%20ONZ%2C%20Warszawa%2C%20Poland&travelmode=walking", modo: "walking", tipo: "pasto" },
        { ora: "~15:00", titolo: "Rientro, check-in vero, doccia e respiro",
          note: "È il momento di riposo dei genitori dopo la levataccia.",
          vai: "https://www.google.com/maps/dir/?api=1&destination=ibis%20Styles%20Warszawa%20City%2C%20Grzybowska%2043%2C%2000-855%20Warszawa%2C%20Poland&travelmode=walking", modo: "walking", tipo: "spost", mail: "https://app.notion.com/p/3b0bdffea7c781faa7e2fe1836fc9aee" },
        { ora: "~16:00", titolo: "Verso la Città Vecchia",
          dove: "Metro M2 da Rondo ONZ a Ratusz Arsenal, poi ~700 m a piedi - 15-20 min",
          note: "A piedi sarebbero 2,6 km / 35 min misurati: troppi dopo un giorno di viaggio.",
          vai: "https://www.google.com/maps/dir/?api=1&destination=Rynek%20Starego%20Miasta%2C%20Warszawa%2C%20Poland&travelmode=transit", modo: "transit", tipo: "spost",
          storia: { testo: "Dove state andando c'e' il Castello Reale. Nato nel Trecento come residenza dei duchi di Masovia, divenne reggia quando nel 1596 Sigismondo III Vasa sposto' la capitale da Cracovia a Varsavia, e prese forma barocca per mano di architetti italiani. I nazisti lo distrussero quasi del tutto: fu ritirato su dal 1971, pagato da una raccolta di soldi fra i cittadini polacchi.",
                    url: "https://poloniadavivere.it/castello-reale-di-varsavia", fonte: "Polonia da Vivere" } },
        { ora: "~16:30", titolo: "Passeggiata in Città Vecchia", dove: "Stare Miasto - ~1h30",
          note: "Piazza del Mercato, esterni del Castello Reale, barbacane, Sirenetta. Ritmo lento, gelato. Pavé sconnesso: scarpe comode.",
          storia: { testo: "Quello che vedete è una ricostruzione. La città vecchia fu rasa al suolo nel 1944, rappresaglia tedesca dopo la Rivolta di Varsavia, e tirata su di nuovo dopo la guerra riusando il più possibile i materiali originali. È patrimonio UNESCO dal 1980: riconosciuta non per l'antichità, ma per come è stata ricostruita.",
                    url: "https://poloniadavivere.it/centro-storico-di-varsavia", fonte: "Polonia da Vivere" }, tipo: "visita" },
        { ora: "~18:15", titolo: "Roof-garden della BUW (giardino sul tetto della biblioteca)",
          dove: "Dobra 56/66 - ~1,3 km dalla Città Vecchia, ~17 min a piedi",
          note: "Verificato: aperto 8:00-20:00 dal 1/5 al 30/9, GRATIS, tutti i giorni. Rampe e ascensori: ok per tutti.",
          vai: "https://www.google.com/maps/dir/?api=1&destination=Biblioteka%20Uniwersytecka%20w%20Warszawie%2C%20Dobra%2056%2F66%2C%20Warszawa%2C%20Poland&travelmode=walking", modo: "walking", tipo: "visita",
          storia: { testo: "Il giardino sul tetto della biblioteca universitaria fu inaugurato nel 2002 e copre oltre un ettaro: e' uno dei giardini pensili piu' grandi d'Europa. Si cammina sopra le sale di lettura, con la citta' e la Vistola sotto.",
                    url: "https://poloniadavivere.it/giardini-biblioteca-universitaria-varsavia", fonte: "Polonia da Vivere" } },
        { ora: "20:30", fisso: true, ok: true, titolo: "Cena - Podwale 25 - CONFERMATA (su MojStolik risulta 'Piwna Kompania')",
          dove: "Podwale 25, Varsavia - 6 persone",
          tel: "+48226356314",
          note: "CONFERMATO via SMS da mojstolik.pl: tavolo per 6 il 4/8 alle 20:30, tenuto 4 ore. Il codice sta in Notion, non qui. 4,9 su 28.006 recensioni. Il locale dichiara una sala da 50 persone. Aperto 11:00-24:00: nessuna corsa la sera dell'arrivo. Sostituisce Stolica (decisione dell'1/8).",
          vai: "https://www.google.com/maps/dir/?api=1&destination=Podwale%2025%2C%20Warszawa%2C%20Poland&travelmode=walking", modo: "walking", tipo: "pasto", mail: "https://app.notion.com/p/3b0bdffea7c781faa7e2fe1836fc9aee" },
        { ora: "~21:30", titolo: "Due passi dopo cena - Gnojna Góra (facoltativo)",
          dove: "In fondo a ul. Celna, dentro la Città Vecchia - ~5 min a piedi",
          note: "Terrazza panoramica sulla scarpata: si vede la Vistola e la riva destra illuminata. Gratis. Nessun orario dichiarato. In alternativa la Piazza del Castello illuminata.",
          vai: "https://www.google.com/maps/dir/?api=1&destination=Gnojna%20Gora%2C%20Warszawa%2C%20Poland&travelmode=walking", modo: "walking", tipo: "pasto",
          storia: { testo: "Nella passeggiata di stasera c'e' il Barbacane, il bastione rotondo eretto nel 1548 a difesa della citta', disegnato dall'italiano Giovanni Battista il Veneziano. Distrutto quasi del tutto in guerra, fu ricostruito fra il 1952 e il 1954 partendo dai disegni originali del Seicento.",
                    url: "https://poloniadavivere.it/barbacane-varsavia", fonte: "Polonia da Vivere" } },
        { ora: "~22:00", titolo: "Rientro in hotel", dove: "Taxi/Bolt ~25 zł - ~12 min",
          note: "La sera NON si torna a piedi (2,6 km): due Bolt e in 12 minuti si è a letto.",
          vai: "https://www.google.com/maps/dir/?api=1&destination=ibis%20Styles%20Warszawa%20City%2C%20Grzybowska%2043%2C%2000-855%20Warszawa%2C%20Poland&travelmode=driving", modo: "driving", tipo: "spost" }
      ],
      pianoB: "Se piove: salta la BUW, Città Vecchia sotto i portici + gelato al coperto. La cena è al chiuso, resta.",
      valvola: "Se il volo ritarda o il gruppo è cotto: si salta la Città Vecchia del pomeriggio e si va dritti a cena in taxi.",
      nota: "Fra la BUW (finisce ~19:00) e la cena delle 20:30 c'è un'ora e mezza libera: era pensata per la cena delle 19:30 da Stolica, poi sostituita. Si riempie con la Città Vecchia o un aperitivo."
    },

    /* ---------------------------------------------------------------- G2 */
    {
      n: 2,
      meteo: { luogo: "Varsavia", lat: 52.23, lon: 21.01 },
      data: "2026-08-05",
      etichetta: "Mercoledì 5 agosto",
      titolo: "Varsavia a fondo - stanziale, tutto coi mezzi",
      base: "Varsavia",
      sveglia: "~7:30",
      carico: "medio",
      cappello: "Zero guida, ma è la giornata più pesante a piedi: ~3h di zoo + ~2h di museo.",
      tappe: [
        { ora: "~7:30", titolo: "Sveglia, colazione in hotel", dove: "ibis Styles", note: "Colazione inclusa.", tipo: "riposo" },
        { ora: "~8:15", titolo: "Verso lo Zoo (riva est, quartiere Praga)",
          dove: "Mezzi pubblici, 5,4 km - 29 min misurati porta a porta",
          note: "Partenza alle 8:15, NON 8:30: alle 8:30 si arriverebbe alle 8:59 per l'apertura delle 9:00, con un minuto di margine. Biglietto WTP zona 1: 4,40 zł per 75 minuti.",
          vai: "https://www.google.com/maps/dir/?api=1&destination=Warszawskie%20ZOO%2C%20Ratuszowa%201%2F3%2C%20Warszawa%2C%20Poland&travelmode=transit", modo: "transit",
          storia: { testo: "Praga sta sull'altra riva della Vistola ed è una delle poche zone di Varsavia risparmiate dalla distruzione: qui le case sono quelle vere, non ricostruite. Per un secolo quartiere operaio e povero, a lungo malfamato, oggi è la zona degli artisti e dei locali.",
                    url: "https://poloniadavivere.it/quartiere-praga-varsavia", fonte: "Polonia da Vivere" }, tipo: "spost" },
        { ora: "09:00", fisso: true, titolo: "Zoo di Varsavia", dove: "Ratuszowa 1/3 - ~2h30-3h",
          note: "Feriale 9:00-18:00, ultimo ingresso 17:00. 45 zł intero / 35 ridotto. Ridotto solo per Emanuele (16) e Raffaele (studente): i quattro adulti pagano 45. Percorsi piani. Biglietti IN CASSA. Conviene esserci all'apertura, quando la fila è la più corta.",
          tel: "+48226194041",
          storia: { testo: "Sotto l'occupazione nazista il direttore dello zoo, Jan Żabiński, e la moglie Antonina trasformarono lo zoo in un rifugio e salvarono più di 300 ebrei. A Jan fu poi riconosciuto il titolo di Giusto tra le Nazioni. È la storia del film «La signora dello zoo di Varsavia».",
                    url: "https://poloniadavivere.it/zoo-varsavia", fonte: "Polonia da Vivere" }, tipo: "visita" },
        { ora: "", titolo: "Villa Zabinski - SOLO dall'esterno",
          note: "L'interno della villa (la casa dei Giusti tra le Nazioni) nei feriali si visita SOLO alle 16:00 con guida: incompatibile con la mattina. Si guarda da fuori girando lo zoo.",
          vai: "https://www.google.com/maps/dir/?api=1&destination=Willa%20Zabinskich%2C%20Ratuszowa%201%2F3%2C%20Warszawa%2C%20Poland&travelmode=walking", modo: "walking",
          storia: { testo: "È la casa dei Żabiński, dentro il recinto dello zoo: il rifugio di cui parla il film. Si vede solo da fuori.",
                    url: "https://poloniadavivere.it/zoo-varsavia", fonte: "Polonia da Vivere" }, tipo: "visita" },
        { ora: "~12:00", titolo: "Rientro verso il centro", dove: "Mezzi - 32 min",
          vai: "https://www.google.com/maps/dir/?api=1&destination=Bar%20mleczny%2C%20Lindleya%2014%2C%20Warszawa%2C%20Poland&travelmode=transit", modo: "transit", tipo: "spost" },
        { ora: "~12:45", titolo: "Pranzo al bar mleczny (mensa popolare storica)",
          dove: "Lindleya 14 - ~75 min",
          note: "Pierogi e zuppe, pasto per 6 attorno ai 15-16 euro TOTALI: genuino ed economico.",
          storia: { testo: "I «bar del latte» sono le mense popolari nate in epoca comunista, sovvenzionate dallo Stato per dare un pasto caldo a chi non poteva permetterselo. Ne restano poche e sono rimaste così: cucina polacca di casa, prezzi bassi, coda.",
                    url: "https://poloniadavivere.it/milk-bar-varsavia", fonte: "Polonia da Vivere" }, tipo: "pasto" },
        { ora: "~14:15", titolo: "Siesta protetta in hotel", dove: "ibis Styles - ~1h15",
          note: "Il caldo di metà pomeriggio d'agosto è riposo, non visite.",
          vai: "https://www.google.com/maps/dir/?api=1&destination=ibis%20Styles%20Warszawa%20City%2C%20Grzybowska%2043%2C%2000-855%20Warszawa%2C%20Poland&travelmode=transit", modo: "transit", tipo: "riposo" },
        { ora: "15:30", fisso: true, titolo: "Verso il Museo dell'Insurrezione",
          dove: "Mezzi, 1,4 km - 10 min, zero cambi",
          note: "Stessa via dell'hotel (43 > 79). A piedi sarebbero 19 min MA c'è un cantiere su Grzybowska: marciapiedi divelti e attraversamenti chiusi fra i civici 43 e 60. Si prendono i mezzi.",
          vai: "https://www.google.com/maps/dir/?api=1&destination=Muzeum%20Powstania%20Warszawskiego%2C%20Grzybowska%2079%2C%20Warszawa%2C%20Poland&travelmode=walking", modo: "walking", tipo: "spost" },
        { ora: "~15:45", titolo: "Museo dell'Insurrezione di Varsavia",
          dove: "Grzybowska 79 - ~2h",
          note: "Mercoledì aperto 10:00-18:00. CHIUDE IL MARTEDI: mercoledì è l'unica occasione del viaggio. 35 zł intero / 30 ridotto (Raffaele ed Emanuele ridotto). Audioguida in ITALIANO 13 zł (10 zł sul proprio telefono). Durata media dichiarata dal museo: 2 ore. Ascensore su ogni piano. Consigliato dai 13 anni in su.",
          storia: { testo: "Il 1° agosto 1944 Varsavia insorse contro l'occupazione nazista. La resistenza tenne 63 giorni. Il 2 ottobre 1944 Hitler ordinò di radere al suolo la città, e l'ordine fu eseguito: è il motivo per cui la Varsavia che vedete è quasi tutta ricostruita.",
                    url: "https://poloniadavivere.it/museo-insurrezione-varsavia", fonte: "Polonia da Vivere" }, tipo: "visita" },
        { ora: "~17:30", titolo: "Museo > rientro in hotel", dove: "Mezzi - ~10 min",
          note: "Uscita alle 17:30 e non 17:45: c'è da riconsegnare l'audioguida. Il museo è nella via dell'hotel.",
          vai: "https://www.google.com/maps/dir/?api=1&destination=ibis%20Styles%20Warszawa%20City%2C%20Grzybowska%2043%2C%2000-855%20Warszawa%2C%20Poland&travelmode=walking", modo: "walking", tipo: "spost" },
        { ora: "17:45-19:30", titolo: "Riposo in hotel", dove: "ibis Styles - ~1h45",
          note: "Decisione dell'1/8: mercoledì si SALTA la Città Vecchia. La si è già vista martedì sera, e questa è la giornata più pesante a piedi.", tipo: "riposo" },
        { ora: "~19:30", titolo: "Hotel > Beef & Pepper",
          dove: "Bolt/taxi, 1,9 km - 8 min in auto (26 a piedi)",
          note: "Rimisurato l'1/8 con l'indirizzo giusto: il locale ha UNA SOLA sede, ul. Nowogrodzka 47A. Margine sulla cena: 30 minuti.",
          vai: "https://www.google.com/maps/dir/?api=1&destination=Beef%20and%20Pepper%2C%20Nowogrodzka%2047A%2C%20Warszawa%2C%20Poland&travelmode=driving", modo: "driving", tipo: "spost" },
        { ora: "20:00", fisso: true, ok: true, titolo: "Cena - Beef & Pepper Steak house - CONFERMATA",
          dove: "ul. Nowogrodzka 47A - 6 persone, sala INSIDE",
          tel: "+48785025025",
          note: "Confermata via mail l'1/8. Nessun codice di prenotazione: il locale la identifica con nome + data + ora. Aperto 12:00-24:00. ATTENZIONE al conto: antipasto + bistecca + bevanda sfonda i 150 zł a testa - restare su Rib-eye Hereford 105 zł senza antipasto, o i secondi non-steak (anatra 89, guancia 89). Richiesta mandata a parte: tavolo normale per 6, non il divanetto.", tipo: "pasto", mail: "https://app.notion.com/p/3b0bdffea7c781faa7e2fe1836fc9aee" },
        { ora: "~22:00", titolo: "Rientro in hotel", dove: "Taxi/Bolt - ~8 min",
          note: "Ultima notte a Varsavia: STASERA SI PREPARANO I BAGAGLI, domattina si parte presto.",
          vai: "https://www.google.com/maps/dir/?api=1&destination=ibis%20Styles%20Warszawa%20City%2C%20Grzybowska%2043%2C%2000-855%20Warszawa%2C%20Poland&travelmode=driving", modo: "driving", tipo: "spost" }
      ],
      pianoB: "Lo Zoo regge la pioggia leggera (molti padiglioni coperti). Col temporale si inverte: Museo dell'Insurrezione al mattino (apre alle 10:00) e Zoo nel pomeriggio se spiove. Il pomeriggio principale non teme la pioggia: il museo è interamente al coperto.",
      valvola: "Da decidere alle 15:15 in hotel, guardando in faccia i genitori. Se il gruppo è cotto, due ore di museo denso ed emotivamente duro sono troppe: si va alla terrazza del Palazzo della Cultura (Plac Defilad 1), 16 min a piedi, ascensore al 30 piano in 19 secondi, zero scale, aperta d'estate fino alle 23:00, 30 zł intero / 25 ridotto, nessuna prenotazione. È l'opzione dove non può andare storto nulla.",
      alternative: "Se una sera non si ha voglia di attraversare la città.",
      alternativeVoci: [
        { n: "Symfonia Smaku", d: "Chlodna 2 — 5 min a piedi. Chiamare per gli orari.", tel: "+48225584524", vai: "https://www.google.com/maps/dir/?api=1&destination=Symfonia%20Smaku%2C%20Chlodna%202%2C%20Warszawa%2C%20Poland&travelmode=walking" },
        { n: "Nova Wola", d: "Rondo Daszynskiego 2 — 12 min a piedi. Cena 17:00-22:30, confermata.", tel: "+48223773801", vai: "https://www.google.com/maps/dir/?api=1&destination=Nova%20Wola%2C%20Rondo%20Daszynskiego%202%2C%20Warszawa%2C%20Poland&travelmode=walking" }
      ]
    },

    /* ---------------------------------------------------------------- G3 */
    {
      n: 3,
      meteo: { luogo: "Masuria", lat: 53.8, lon: 21.57 },
      data: "2026-08-06",
      etichetta: "Giovedì 6 agosto",
      titolo: "Ritiro auto > Masuria > spa > cena al resort",
      base: "Masuria",
      sveglia: "~7:15",
      carico: "medio-alto",
      cappello: "Il vincolo della giornata è uno solo: alle 9:00 in punto si ritirano le auto. NIENTE BARCA: la crociera è annullata, il pomeriggio va alla spa. È l'unico pomeriggio libero di tutto il viaggio.",
      tappe: [
        { ora: "~7:15", titolo: "Sveglia, colazione, check-out", dove: "ibis Styles - ~1h",
          note: "Scendere già pronti con i bagagli. Rilascio camera entro le 11:00, ma si parte prima.", tipo: "riposo" },
        { ora: "~8:20", titolo: "ibis > Novotel Centrum (ufficio Europcar)",
          dove: "2 taxi/Bolt, 2,9 km - 13 min (20 col traffico peggiore)",
          note: "8:20 e NON 8:30: due taxi da chiamare, sei valigie da caricare, e un ritiro alle 9:00 in punto. A piedi sarebbero 28 minuti: impensabile con sei valigie.",
          vai: "https://www.google.com/maps/dir/?api=1&destination=Novotel%20Warszawa%20Centrum%2C%20Marszalkowska%2094%2F98%2C%2000-510%20Warszawa%2C%20Poland&travelmode=driving", modo: "driving", tipo: "spost" },
        { ora: "09:00", fisso: true, titolo: "RITIRO AUTO - Europcar MPOINT + auto degli zii",
          dove: "Novotel Centrum, Marszalkowska 94/98 - 45-60 min",
          attenzione: "SERVONO, TUTTI INTESTATI A CARLO: patente + carta d'identità o passaporto (la patente da sola NON basta) + la STESSA carta di credito con cui è stata pagata la prenotazione. Bloccano 300 euro di deposito. Se salta, saltano l'auto e i giorni dal 6 all'11.",
          tel: "+48665301600",
          note: "Renault Clio, prepagata. Secondo guidatore e Premium Protection già inclusi. Ufficio presidiato 9:00-16:59, nessun supplemento. Un 'MPOINT' è un punto di consegna dentro l'hotel e non è pubblicato se ci si presenta alla reception o al garage: telefonare prima.", tipo: "spost", mail: "https://app.notion.com/p/3b0bdffea7c781faa7e2fe1836fc9aee" },
        { ora: "~9:45", titolo: "Varsavia > Robert's Port (Mikolajki)",
          dove: "253 km, S8 > S61, zero pedaggi - 3h14 normale, fino a 4h04 col traffico peggiore",
          note: "Misurato su Google e confermato da OSRM (3h28). Cambio-guida a metà.",
          vai: "https://www.google.com/maps/dir/?api=1&destination=Hotel%20Robert%27s%20Port%2C%20Stare%20Sady%204%2C%2011-730%20Mikolajki%2C%20Poland&travelmode=driving", waze: "https://waze.com/ul?ll=53.836838,21.546502&navigate=yes", modo: "driving", tipo: "spost" },
        { ora: "~11:30", titolo: "Sosta benessere + spuntino (bagno, caffè)",
          dove: "MOP zona Ostrow Maz. / Lomza sulla S8 - 20 min",
          note: "Dopo circa 1h45 di guida, area ampia.", tipo: "visita" },
        { ora: "~13:20", titolo: "Arrivo Robert's Port, check-in",
          dove: "Stare Sady 4, Mikolajki - ~45 min",
          note: "Arrivo realistico 13:20 con traffico normale, ~14:10 nel caso peggiore. Domek Zeglarza, già pagato, intestato a Carlo. Parcheggio in superficie sul posto.",
          storia: { testo: "La Masuria ha oltre 2.000 laghi, scavati dall'ultima glaciazione. Fu terra dei prussiani baltici, conquistata nel Duecento dai Cavalieri Teutonici, poi Ducato di Prussia e Prussia Orientale: tedesca fino al 1945. Per questo i nomi dei paesi sono cambiati tutti dopo la guerra.",
                    url: "https://poloniadavivere.it/terra-dei-laghi-della-masuria", fonte: "Polonia da Vivere" }, tipo: "spost", mail: "https://app.notion.com/p/3b0bdffea7c781faa7e2fe1836fc9aee" },
        { ora: "~14:10", titolo: "Pranzo leggero al resort", dove: "Robert's Port - ~45 min",
          note: "NON SALTARLO: dalla colazione delle 7:15 sono già sette ore, e la cena è alle 19:30. Il ristorante è aperto dalle 12:00.", tipo: "pasto" },
        { ora: "15:00-19:00", titolo: "SPA - il cuore della giornata", dove: "Robert's Port - ~4h",
          note: "Piscina coperta, jacuzzi, sauna, hammam, spiaggia sul lago. Incluso nel soggiorno. È l'unico pomeriggio libero di tutto il viaggio ed è il motivo per cui è stato scelto questo hotel. Nel caso peggiore (arrivo 14:10) si accorcia di un'ora e regge lo stesso.", tipo: "riposo" },
        { ora: "19:30", fisso: true, titolo: "Cena al ristorante dell'hotel",
          dove: "Robert's Port - non serve l'auto",
          tel: "+48875065400",
          note: "Aperto tutti i giorni 12:00-22:00 (confermato dalla loro mail del 27/07). Nessuna corsa: si cena dove si dorme. Bozza di richiesta pronta in Gmail. Se le 19:30 non fossero disponibili va bene qualsiasi ora fra le 18:00 e le 20:00. Se non rispondono, al limite il tavolo si chiede al check-in.", tipo: "pasto", mail: "https://app.notion.com/p/3b0bdffea7c781faa7e2fe1836fc9aee" },
        { ora: "~21:30", titolo: "Serata libera al resort",
          note: "Il tramonto (~20:45) si vede dalla spiaggia del resort, sul lago. Domani sveglia alle 7:00: stasera si va a dormire presto.", tipo: "riposo" }
      ],
      pianoB: "Non ne serve più uno: la giornata è ormai al coperto (spa + ristorante dell'hotel), il tempo non la tocca.",
      valvola: "Se il traffico fosse quello pessimistico (arrivo 14:10) si accorcia la spa di un'ora. La cena delle 19:30 non si tocca ed è comunque spostabile fino alle 20:00.",
      nota: "Stasera va telefonato il kayak per domattina: +48 600 029 035. E vanno preparati 360 zł in contanti."
    },

    /* ---------------------------------------------------------------- G4 */
    {
      n: 4,
      meteo: { luogo: "Masuria", lat: 53.8, lon: 21.57 },
      data: "2026-08-07",
      etichetta: "Venerdì 7 agosto",
      titolo: "Kayak sulla Krutynia + Tana del Lupo + cena memorabile",
      base: "Masuria",
      sveglia: "~7:00",
      carico: "ALTO",
      cappello: "La giornata più intensa: ~151 km di guida frammentata e ~6h di attività. Nel ramo di default (senza Swieta Lipka) dura ~10h30, dalle 8:00 alle 21:45.",
      tappe: [
        { ora: "~7:00", titolo: "Sveglia, colazione presto", dove: "Robert's Port - ~45 min",
          note: "Giornata lunga: partire carichi.", tipo: "riposo" },
        { ora: "~8:00", titolo: "Resort > Krutyn (base kayak)",
          dove: "27 km in auto - 28 min",
          note: "Partenza 8:00 e NON 8:10: sul posto servono 30 minuti per parcheggiare, contare i 360 zł in contanti e vestire sei persone.",
          vai: "https://www.google.com/maps/dir/?api=1&destination=Krutyn%202B%2C%2011-710%20Piecki%2C%20Poland&travelmode=driving", waze: "https://waze.com/ul?ll=53.690172,21.435485&navigate=yes", modo: "driving", tipo: "spost" },
        { ora: "09:00", fisso: true, titolo: "Discesa in kayak sulla Krutynia (Krutyn > Rosocha, 6 km)",
          dove: "Fiume Krutynia - 2-3h in acqua",
          attenzione: "360 zł IN CONTANTI, da pagare sul posto PRIMA della discesa. Se piove e non si va, non si è ancora pagato nulla: il rischio economico è zero.",
          tel: "+48600029035",
          note: "Operatore Sakowscy / Wan Plac, base Krutyn 2B. Un dipendente parla italiano. Fiume facile, corrente dolce, nessuna rapida. 3 kayak doppi x 120 zł. Tutto incluso (attrezzatura + recupero). Ci si bagna e si sale/scende dal kayak: gli zii valutino. Loro hanno indicato le 9:00, non le 8:45.",
          storia: { testo: "La Krutynia è il fiume più amato dai canoisti polacchi: nasce dai laghi della Masuria e scende lenta dentro la foresta. Non è una discesa sportiva, è una passeggiata sull'acqua.",
                    url: "https://poloniadavivere.it/terra-dei-laghi-della-masuria", fonte: "Polonia da Vivere" }, tipo: "spost", mail: "https://app.notion.com/p/3b0bdffea7c781faa7e2fe1836fc9aee" },
        { ora: "~12:00", titolo: "Cambio, pranzo", dove: "Krutyn - ~75 min",
          note: "Non comprimere: si è bagnati e affamati.", tipo: "pasto" },
        { ora: "~13:30", titolo: "Krutyn > Tana del Lupo (Gierloz)",
          dove: "61 km in auto - 1h03 (1h14 col traffico peggiore)",
          note: "Bagni e parcheggio all'ingresso.",
          vai: "https://www.google.com/maps/dir/?api=1&destination=Wilczy%20Szaniec%2C%20Gierloz%2C%20Poland&travelmode=driving", waze: "https://waze.com/ul?ll=54.079037,21.493082&navigate=yes", modo: "driving", tipo: "spost" },
        { ora: "~14:40", titolo: "Wilczy Szaniec - la Tana del Lupo",
          dove: "Gierloz - ~2h a piedi nel bosco (terreno piano)",
          note: "Il quartier generale di Hitler nel bosco. Agosto 8:00-20:00 tutti i giorni. 30 zł intero / 25 ridotto + parcheggio 15 zł. Audioguida 10 zł oppure app gratuita 'Wilczy Szaniec'. Ridotto solo per Emanuele e Raffaele.",
          storia: { testo: "Quartier generale di Hitler sul fronte orientale, costruito nel 1940 dentro la foresta e usato dal 1941 al 1944. Qui, il 20 luglio 1944, il colonnello Stauffenberg piazzò la bomba che doveva ucciderlo: l'attentato fallì. Nel 1945, in ritirata, i tedeschi fecero saltare il complesso — quello che si visita sono quelle rovine.",
                    url: "https://poloniadavivere.it/tana-del-lupo-polonia", fonte: "Polonia da Vivere" }, tipo: "visita" },
        { ora: "16:40", titolo: "BIVIO DEL POMERIGGIO - si sceglie qui",
          note: "Ramo A (default): si rientra al resort. Ramo B: Swieta Lipka.", tipo: "spost" },
        { ora: "~16:40 (A)", titolo: "RAMO A - Rientro diretto al resort",
          dove: "Gierloz > Robert's Port, 51 km - 55 min (1h04 peggiore)",
          note: "Arrivo al resort ~17:35, con un'ora di spa prima di cena. È il ramo consigliato.",
          vai: "https://www.google.com/maps/dir/?api=1&destination=Hotel%20Robert%27s%20Port%2C%20Stare%20Sady%204%2C%2011-730%20Mikolajki%2C%20Poland&travelmode=driving", waze: "https://waze.com/ul?ll=53.836838,21.546502&navigate=yes", modo: "driving", tipo: "spost" },
        { ora: "~16:40 (B)", titolo: "RAMO B - Swieta Lipka (opzionale, di default si salta)",
          dove: "22 km da Gierloz - 28 min",
          note: "I mini-concerti d'organo feriali sono alle 10:00, 11:00, 14:00, 15:30 e 17:00. Arrivando alle 17:10 il concerto delle 17:00 è già iniziato: per prenderlo bisogna tagliare mezz'ora alla Tana del Lupo e partire alle 16:20. Basilica gratis, organo a offerta libera. Il concerto si tiene se c'è un gruppo di ~20 persone. Poi rientro al resort in 47 min, arrivo ~18:55: si va a cena quasi diretti, senza spa.",
          vai: "https://www.google.com/maps/dir/?api=1&destination=Sanktuarium%20Swieta%20Lipka%2C%20Poland&travelmode=driving", waze: "https://waze.com/ul?ll=54.025236,21.217228&navigate=yes", modo: "driving",
          storia: { testo: "«Święta Lipka» vuol dire tiglio santo: la leggenda racconta di un condannato a morte che scolpì una Madonna e la mise su un tiglio, e ottenne la grazia. Il santuario barocco che ne nacque ha un organo con le statue che si muovono quando suona.",
                    url: "https://www.polonia.travel/it/warminsko-mazurskie-varmia-masuria/", fonte: "Polonia.travel (ente del turismo)" }, tipo: "spost" },
        { ora: "~19:00", titolo: "Resort > cena", dove: "5,8 km in auto - 9 min",
          note: "Partenza 19:00 e NON 19:15: sei minuti col parcheggio non sono un margine.",
          vai: "https://www.google.com/maps/dir/?api=1&destination=Restauracja%20Spizarnia%2C%20Plac%20Handlowy%2014%2C%20Mikolajki%2C%20Poland&travelmode=driving", waze: "https://waze.com/ul?ll=53.802203,21.574038&navigate=yes", modo: "driving", tipo: "pasto" },
        { ora: "19:30", fisso: true,  titolo: "Cena - Spizarnia Mazury (NON si prenota: si va e si aspetta)",
          dove: "Plac Handlowy 14, Mikolajki",
          attenzione: "NON PRENDONO PRENOTAZIONI. Risposta del locale del 2/8 (Katarzyna Bujanowska, direttrice): «we do not do reservations… we seat guests on an ongoing basis». Probabile entrare senza attesa, ma nessuna garanzia. LA CUCINA CHIUDE GLI ORDINI ALLE 21:30: presentarsi entro le 20:30 per stare tranquilli.",
          tel: "+48451101330",
          note: "Spizarnia: aperta tutti i giorni 12:00-22:00 in agosto (l'orario 12-20 sul sito è di bassa stagione). Istituzione dei laghi da oltre 20 anni, 94% la raccomanda su 506 opinioni. Pesce di lago e selvaggina, ~24-32 euro a testa. Altro numero: +48 509 188 057. Il numero (87) 421 52 18 che gira sui portali NON è sul sito ufficiale: non usarlo. w Zatoce: +48 87 421 90 00 (è un hotel, la reception risponde sempre).", tipo: "pasto", mail: "https://app.notion.com/p/3b0bdffea7c781faa7e2fe1836fc9aee" },
        { ora: "~21:45", titolo: "Rientro al resort", dove: "~9 min in auto",
          note: "Ultima notte in Masuria: CARICARE LE AUTO STASERA, domattina si parte alle 7:00.",
          vai: "https://www.google.com/maps/dir/?api=1&destination=Hotel%20Robert%27s%20Port%2C%20Stare%20Sady%204%2C%2011-730%20Mikolajki%2C%20Poland&travelmode=driving", waze: "https://waze.com/ul?ll=53.836838,21.546502&navigate=yes", modo: "driving", tipo: "spost" }
      ],
      pianoB: "Il kayak si fa anche con pioggia leggera (ci si bagna comunque), ma salta col temporale o col vento forte. In quel caso: Tana del Lupo al mattino (il bosco ripara) e Swieta Lipka al pomeriggio, prendendo il concerto delle 14:00 o delle 15:30.",
      valvola: "Salta Swieta Lipka (già di default): la giornata scende a ~7h e si rientra per la spa. Se anche il kayak stanca, la Tana del Lupo da sola regge la giornata."
    },

    /* ---------------------------------------------------------------- G5 */
    {
      n: 5,
      meteo: { luogo: "Malbork e Danzica", lat: 54.35, lon: 18.65 },
      data: "2026-08-08",
      etichetta: "Sabato 8 agosto",
      titolo: "239 km > Malbork > pranzo a Bistro na Fali > Danzica",
      base: "Danzica",
      sveglia: "~6:00",
      carico: "ALTO",
      cappello: "Si parte alle 7:00. La tratta è 239 km: 2h40 normale, 3h09 col traffico peggiore. Con i biglietti in cassa non c'è più uno slot da rincorrere, ma la nuova variabile è la FILA ALLE CASSE di un sabato d'agosto.",
      tappe: [
        { ora: "~6:00", titolo: "Sveglia, colazione presto, check-out", dove: "Robert's Port - ~1h",
          attenzione: "Non è mai stato chiesto se la colazione apre prima delle 7:00. Se non apre serve un cestino: telefonare +48 87 429 84 00.",
          note: "Auto già cariche da ieri sera.", tipo: "riposo" },
        { ora: "~7:00", titolo: "Mikolajki > Malbork",
          dove: "239 km sulla S7, zero pedaggi - 2h40 normale, fino a 3h09",
          note: "Misurato su Google e OSRM. Cambio-guida a metà, strada scorrevole. Per un cuscinetto reale anche nel caso peggiore: partire alle 6:45 o accorciare la sosta a 10 minuti.",
          vai: "https://www.google.com/maps/dir/?api=1&destination=Zamek%20w%20Malborku%2C%20Staroscinska%201%2C%2082-200%20Malbork%2C%20Poland&travelmode=driving", waze: "https://waze.com/ul?ll=54.040887,19.029699&navigate=yes", modo: "driving", tipo: "spost" },
        { ora: "~8:45", titolo: "Sosta benessere", dove: "MOP zona Nidzica / Olsztynek sulla S7 - 20 min",
          note: "Dopo circa 1h45 di guida.", tipo: "visita" },
        { ora: "10:00-10:30", titolo: "Arrivo Malbork, parcheggio, biglietti",
          dove: "ul. Kosciuszki / Zamkowa - ~30 min",
          note: "Nome e tariffa del parcheggio non sono pubblicati online: sono parcheggi a pagamento attorno al castello, lato Staroscinska/Kosciuszki. Si vede sul posto.", tipo: "spost" },
        { ora: "~11:00", titolo: "Castello di Malbork (Trasa Historyczna, audioguida in italiano)",
          dove: "Malbork - ~3h30 a piedi",
          note: "Mar-dom 9:00-20:00, ultimo ingresso 16:30: sabato aperto. 80 zł intero / 60 ridotto, audioguida italiana INCLUSA. Biglietti IN CASSA (decisione del 31/07). La visita parte dal Plac 60-lecia Muzeum, DAVANTI ALLE CASSE, non dal portone: l'audioguida si ritira lì ed è lì che si sceglie l'italiano. Torre: biglietto a parte, 17/13 zł = 94 zł per sei, si sale 11:00-18:15.",
          storia: { testo: "Il più grande castello del mondo costruito in mattoni. Lo tirarono su i Cavalieri Teutonici fra il 1270 e il 1404 e ne fecero la loro capitale, sede del Gran Maestro dell'Ordine. Patrimonio UNESCO dal 1997.",
                    url: "https://www.polonia.travel/it/i-segreti-nascosti-nella-monumentale-fortezza-di-malbork/", fonte: "Polonia.travel (ente del turismo)" }, tipo: "visita", mail: "https://app.notion.com/p/3b0bdffea7c781faa7e2fe1836fc9aee" },
        { ora: "~14:15", fisso: true, aperta: true, titolo: "Pranzo - Bistro na Fali (si decide sul posto)",
          dove: "ul. Walowa 10, Malbork - ~75 min, ~9 min in auto dal castello",
          attenzione: "Mail inviata l'1/8, nessuna risposta al 2/8. Il locale è aperto da mezzogiorno tutti i giorni: nel peggiore dei casi ci si presenta e basta, la capienza dichiarata è 2-35 persone. NEL NAVIGATORE METTERE 'ul. Walowa 10': alcuni portali scrivono 'Kaldowo Wies 10' - è lo stesso posto (quartiere sulla sponda ovest del Nogat) ma l'indirizzo giusto è Walowa.",
          tel: "+48534610670",
          note: "NON prenotato, scelta del 3/8: si arriva e si vede. Se e' pieno non si aspetta, si tira dritto verso Danzica e si mangia li' arrivando prima. L'ex Karczma Zamczysko, rinominata da Magda Gessler nel 2016. 4,8 su 4.909 recensioni, #2 di 11 a Malbork. Dal castello: 1,1 km / 15 min a piedi, oppure 3,2 km / 9 min in auto. E sta sulla strada: da lì al Sadova sono 58,2 km / 44 min contro 61 km / 51 min dal castello - la sosta fa risparmiare 7 minuti. Tetto orario: 15:00, alle 15:45 si deve ripartire. Secondo numero: +48 601 624 661. La facciata del castello si fotografa dall'altra sponda del Nogat.",
          vai: "https://www.google.com/maps/dir/?api=1&destination=Bistro%20na%20Fali%2C%20Walowa%2010%2C%2082-200%20Malbork%2C%20Poland&travelmode=walking", modo: "walking", tipo: "pasto" },
        { ora: "~15:45", titolo: "Malbork > Hotel Sadova",
          dove: "61 km in auto, zero pedaggi - 49 min (1h00 pessimistico)",
          vai: "https://www.google.com/maps/dir/?api=1&destination=Hotel%20Sadova%2C%20Lakowa%2060%2C%2080-769%20Gdansk%2C%20Poland&travelmode=driving", waze: "https://waze.com/ul?ll=54.345705,18.664727&navigate=yes", modo: "driving", tipo: "spost" },
        { ora: "~16:45", titolo: "Check-in Hotel Sadova (3 notti), riposo",
          dove: "Lakowa 60, Danzica - ~45 min",
          attenzione: "È UN MONOLOCALE PER 4, non tre camere: Raffaele ed Emanuele condividono un matrimoniale. Verificare la configurazione dei letti al check-in. Parcheggio 70 zł al giorno per auto, NON prenotabile: 2 auto x 3 giorni = ~420 zł. Non è mai stato chiesto se c'è posto durante il Jarmark né qual è il ripiego.",
          tel: "+48583823030",
          note: "Già pagato, non rimborsabile, intestato a Raffaele. Colazione ESCLUSA (85 zł a persona). Tassa di soggiorno 41,52 zł in loco.", tipo: "riposo", mail: "https://app.notion.com/p/3b0bdffea7c781faa7e2fe1836fc9aee",
          storia: { testo: "Siete arrivati in citta' durante la Fiera di San Domenico. La tradizione parte dal 1260, quando papa Alessandro IV permise ai domenicani di Danzica di concedere indulgenze: attorno alla festa nacque il mercato, e da allora si ripete ogni estate per tre settimane. E' il motivo per cui in centro trovate folla, bancarelle e concerti.",
                    url: "https://www.gazzettaitalia.pl/polonia-oggi-758-fiera-di-san-domenico-a-danzica/", fonte: "Gazzetta Italia" } },
        { ora: "~18:15", titolo: "Passeggiata serale lungo la Motlawa",
          dove: "Dlugi Targ, la gru Zuraw - ~45 min, 13 min a piedi",
          note: "LA PASSEGGIATA FINISCE ALLE 19:00, non alle 19:15: dal centro al Kubicki sono 19 minuti a piedi, e chiudendo alle 19:15 si arrivava alle 19:34 per un tavolo delle 19:30. Fiera di San Domenico in corso su tutti e tre i giorni: folla e ristoranti pieni. NON mangiare sulla via Dluga: è la trappola per turisti.",
          vai: "https://www.google.com/maps/dir/?api=1&destination=Dlugi%20Targ%2C%20Gdansk%2C%20Poland&travelmode=walking", modo: "walking",
          storia: { testo: "Danzica ha mille anni ed è finita due volte al centro della storia del mondo: qui il 1° settembre 1939 cominciò la Seconda guerra mondiale, e qui nel 1980 nacque Solidarność, il sindacato che aprì la prima crepa nel blocco sovietico.",
                    url: "https://www.polonia.travel/it/danzica", fonte: "Polonia.travel (ente del turismo)" }, tipo: "visita" },
        { ora: "19:30", fisso: true, ok: true, titolo: "Cena - Restauracja Kubicki - CONFERMATA",
          dove: "Wartka 5, sul Motlawa - 19 min a piedi (1,4 km)",
          tel: "+48583010050",
          note: "Confermata dal locale l'1/8. Aperto sabato 12:00-22:00, ultimo ordine ~21:30. Il più antico di Danzica, dal 1918, 4,4/5. Golonka, zurek, anatra. ~20-28 euro a testa.",
          vai: "https://www.google.com/maps/dir/?api=1&destination=Restauracja%20Kubicki%2C%20Wartka%205%2C%20Gdansk%2C%20Poland&travelmode=walking", modo: "walking", tipo: "pasto", mail: "https://app.notion.com/p/3b0bdffea7c781faa7e2fe1836fc9aee" },
        { ora: "~21:45", titolo: "Rientro a piedi", dove: "Sadova - ~19 min",
          vai: "https://www.google.com/maps/dir/?api=1&destination=Hotel%20Sadova%2C%20Lakowa%2060%2C%2080-769%20Gdansk%2C%20Poland&travelmode=walking", modo: "walking", tipo: "spost" }
      ],
      pianoB: "Malbork è in gran parte al chiuso: la pioggia non lo ferma.",
      valvola: "L'ultimo ingresso al castello è alle 16:30, quindi anche con un'ora di ritardo si entra. Se il gruppo è stanco si fa il percorso corto (~2h invece di 3h30) e si arriva prima a Danzica.",
      alternative: "Se il Kubicki saltasse, questi due sono a due passi. Se invece chiudesse Bistro na Fali (il pranzo), si mangia a Danzica arrivando prima: la pizzeria Papas, unica altra nominata dai video, è stroncata.",
      alternativeVoci: [
        { n: "Gvara", d: "Chlebnicka 48/51 — 4,6 su 3.562 recensioni.", tel: "+48795889288", vai: "https://www.google.com/maps/dir/?api=1&destination=Gvara%2C%20Chlebnicka%2048%2F51%2C%20Gdansk%2C%20Poland&travelmode=walking" },
        { n: "Brovarnia", d: "Szafarnia 9 — birreria storica.", tel: "+48726030400", vai: "https://www.google.com/maps/dir/?api=1&destination=Brovarnia%20Gdansk%2C%20Szafarnia%209%2C%20Gdansk%2C%20Poland&travelmode=walking" }
      ]
    },

    /* ---------------------------------------------------------------- G6 */
    {
      n: 6,
      meteo: { luogo: "Leba e le dune", lat: 54.76, lon: 17.55 },
      data: "2026-08-09",
      etichetta: "Domenica 9 agosto",
      titolo: "Dune di Leba + foche - la giornata che si è alleggerita",
      base: "Danzica",
      sveglia: "~8:00 (lenta)",
      carico: "medio",
      cappello: "È la mossa che rompe la sequenza di mattine presto. Due misure hanno migliorato la giornata: Danzica-Leba è 1h27 e non 2h, e il Sea Park in agosto chiude alle 19:00 e non alle 17:00.",
      tappe: [
        { ora: "~8:00", titolo: "Sveglia, colazione con calma", dove: "Sadova - ~1h",
          note: "Si recupera dalle due giornate piene.", tipo: "riposo" },
        { ora: "~9:15", titolo: "Danzica > Rabka (ingresso dune)",
          dove: "113 km, S6 > DW214, zero pedaggi - 1h27 (fino a 1h46)",
          note: "Misurato, OSRM conferma 1h34. Cambio-guida.",
          vai: "https://www.google.com/maps/dir/?api=1&destination=R%C4%85bka%2C%2084-360%20%C5%81eba%2C%20Poland&travelmode=driving", waze: "https://waze.com/ul?ll=54.754143,17.515967&navigate=yes", modo: "driving", tipo: "spost" },
        { ora: "~10:15", titolo: "Micro-sosta facoltativa", dove: "Lebork sulla S6 - 15 min",
          note: "Bar e parcheggio, spezza il tratto.", tipo: "visita" },
        { ora: "~11:00", titolo: "Arrivo Rabka, ingresso al parco, scelta del mezzo",
          dove: "Parco Slowinski - ~30 min",
          attenzione: "Da Rabka al piede della duna Lacka sono ~5,5 km, NON 1,8 come diceva il vecchio piano. Andata e ritorno a piedi = 11 km sulla sabbia sotto il sole d'agosto: con quattro over-50 il melex (navetta elettrica) è la scelta giusta, o le bici.",
          tel: "+48886354555",
          note: "Ingresso parco 10 zł intero / 5 ridotto. Melex ~50-70 zł a testa andata e ritorno. Parcheggio di Rabka ~8-9 zł all'ora. ATTENZIONE: il melex elettrico è spesso fermo, va messo in conto un piano B a piedi o in bici (sterrato piano).", tipo: "spost" },
        { ora: "~11:30", titolo: "Dune mobili (Wydma Lacka) - salita e panorama",
          dove: "Parco Slowinski - ~2h30",
          note: "La salita è PIÙ FACILE DOPO LA PIOGGIA (sabbia compatta): col sole secco si affonda. Cappello e acqua obbligatori. Chi non se la sente può fermarsi al panorama basso.",
          storia: { testo: "È la più grande distesa di dune mobili d'Europa: 500 ettari. La più alta, la Łącka Góra, arriva a 42 metri. Si spostano verso est di 10 metri l'anno e nei secoli hanno sepolto due villaggi interi, con le loro case.",
                    url: "https://www.polonia.travel/it/il-parco-nazionale-slowinski/", fonte: "Polonia.travel (ente del turismo)" }, tipo: "visita" },
        { ora: "~14:00", titolo: "Rientro dalla duna verso l'uscita del parco", dove: "~40 min",
          note: "Sono di nuovo 5,5 km: il rientro non è istantaneo, va contato.", tipo: "spost" },
        { ora: "~14:40", titolo: "Pranzo veloce a Leba", dove: "Centro di Leba - ~40 min",
          attenzione: "Sulle friggitorie di Leba due-tre video indipendenti concordano su una cosa: si spaccia il CZARNIAK per merluzzo (dorsz). La linea che conta non è centro-contro-fuori, è PREZZO FISSO (zestaw) CONTRO PESCE VENDUTO A PESO: è a peso che si gonfia il conto.",
          note: "Nessuna prenotazione, deciso l'1/8. Alle 15:05 si riparte per le foche. È stata valutata e scartata Ewa Zaprasza a Sasino (4,9 su 8.265, l'unico locale di tutto il lavoro che dichiari di accogliere un gruppo): geograficamente perfetta, ma faceva arrivare al Sea Park alle 16:30 e saltare lo spettacolo delle 16:00.",
          vai: "https://www.google.com/maps/dir/?api=1&destination=Leba%2C%20Poland&travelmode=walking", modo: "walking", tipo: "pasto",
          storia: { testo: "Leba e' un porto di pescatori diventato luogo di villeggiatura sul Baltico. Sta incastrata fra il mare e il lago Lebsko, all'ingresso del parco delle dune: il paese esiste per quello, e d'estate vive di quello.",
                    url: "https://www.polonia.travel/it/il-parco-nazionale-slowinski/", fonte: "Polonia.travel (ente del turismo)" } },
        { ora: "~15:05", titolo: "Leba > Sea Park Sarbsk", dove: "10 km in auto - 15 min",
          note: "Partenza 15:05 e NON 15:20: sei biglietti alla cassa prima dello spettacolo delle 16:00, di domenica, in agosto. Arrivo ~15:20, cioè 40 minuti per parcheggiare e fare i biglietti.",
          vai: "https://www.google.com/maps/dir/?api=1&destination=Sea%20Park%2C%20ul.%20Foki%201%2C%20Sarbsk%2C%20Poland&travelmode=driving", waze: "https://waze.com/ul?ll=54.737595,17.647537&navigate=yes", modo: "driving", tipo: "spost" },
        { ora: "~15:40", titolo: "Sea Park Sarbsk (foche)",
          dove: "ul. Foki 1, Sarbsk - ~1h30-2h",
          note: "Attrazione seduta, comoda per tutti. In luglio-agosto aperto 9:00-19:00. Spettacolo foche alle 16:00 e, in alta stagione, ANCHE ALLE 18:00. Arrivare dopo le 16:00 non rovina la giornata: c'è il pokaz delle 18:00 e il parco chiude alle 19:00 - è questa la vera rete di sicurezza. 119 zł intero / 99 ridotto + parcheggio 20 zł. ATTENZIONE: qui il ridotto studenti NON vale.", tipo: "visita" },
        { ora: "~17:45", titolo: "Rientro a Danzica",
          dove: "112 km in auto - 1h26 (fino a 1h47)",
          note: "Cambio-guida, sosta a Lebork se serve.",
          vai: "https://www.google.com/maps/dir/?api=1&destination=Hotel%20Sadova%2C%20Lakowa%2060%2C%2080-769%20Gdansk%2C%20Poland&travelmode=driving", waze: "https://waze.com/ul?ll=54.345705,18.664727&navigate=yes", modo: "driving", tipo: "spost" },
        { ora: "~19:30", titolo: "Rientro al Sadova, piscina/spa", dove: "Danzica",
          note: "Giornata di guida lunga, sera scarica.", tipo: "riposo" },
        { ora: "20:00", ok: true, fisso: true, aperta: true, titolo: "Cena - True - CONFERMATA",
          dove: "Chmielna 10, Isola dei Granai - 0,9 km dal Sadova, 12 min a piedi (il più vicino di tutti)",
          attenzione: "Mail inviata l'1/8, nessuna risposta al 2/8. Se True salta, la rete di sicurezza è Papieroovka (il ristorante dentro il Sadova) - ma l'hotel ha detto il 27/07 che nei weekend è pieno e NON basta avvisare la reception: va prenotata davvero.",
          tel: "+48727600601",
          note: "CONFERMATO dal locale su WhatsApp il 3/8 alle 22:29: «There is a table available and I'm gonna book that table right away». Tavolo per 6, nome Antoci. La mail dell'1/8 non ha mai avuto risposta: ha risposto WhatsApp in mezza giornata. 4,6 su 914 recensioni, confermato nella Guida MICHELIN (selezione ufficiale di Danzica: doppia-euro, 'Meats and Grills', non stellato). Domenica 13:00-22:00. Il Galar al tramonto è stato ESCLUSO l'1/8: domenica è già la giornata più piena e sposterebbe l'ora di cena. Papieroovka (piano B): dentro l'hotel, zero spostamenti, domenica 13:00-22:00, cucina regionale e la più grande cider-house della Polonia (~30 sidri), ~18-28 euro a testa, reception +48 58 382 30 30. Altre alternative casual già valutate: Pierogarnia Mandu (ul. Elzbietanska 4/8), Mon Balzac (ul. Chmielna 10).",
          vai: "https://www.google.com/maps/dir/?api=1&destination=True%20Restaurant%2C%20Chmielna%2010%2C%20Gdansk%2C%20Poland&travelmode=walking", modo: "walking", tipo: "pasto", mail: "https://app.notion.com/p/3b0bdffea7c781faa7e2fe1836fc9aee" }
      ],
      pianoB: "Con pioggia leggera le dune sono PIÙ FACILI. Col temporale: solo Sea Park (al coperto) o giornata-città a Danzica.",
      valvola: "Se la giornata si allunga, l'elemento sacrificabile è il Sea Park, NON le dune. Ma con la chiusura alle 19:00 verificata è molto meno probabile doverlo tagliare."
    },

    /* ---------------------------------------------------------------- G7 */
    {
      n: 7,
      meteo: { luogo: "Danzica", lat: 54.35, lon: 18.65 },
      data: "2026-08-10",
      etichetta: "Lunedì 10 agosto",
      titolo: "Danzica, galeone a Westerplatte, Sopot, cena di chiusura",
      base: "Danzica",
      sveglia: "~8:30 (lenta)",
      carico: "medio",
      cappello: "Penultimo giorno, ritmo rilassato, niente guida lunga: le auto restano ferme all'hotel tutto il giorno.",
      tappe: [
        { ora: "~8:30", titolo: "Sveglia, colazione con calma", dove: "Sadova - ~1h", tipo: "riposo" },
        { ora: "~9:45", titolo: "Danzica a fondo: Basilica di Santa Maria, via Reale, l'ambra al Jarmark",
          dove: "Centro storico - ~1h45, 13 min a piedi",
          note: "Jarmark sw. Dominika confermato dal 25/7 al 16/8: oggi è in pieno svolgimento. La torre di Santa Maria sono 408 gradini senza ascensore: solo per chi se la sente. Ambra con certificato dagli artigiani della fiera.",
          vai: "https://www.google.com/maps/dir/?api=1&destination=Dlugi%20Targ%2C%20Gdansk%2C%20Poland&travelmode=walking", modo: "walking",
          storia: { testo: "La basilica di Santa Maria fu costruita fra il 1343 e il 1502 ed è una delle chiese in mattoni più grandi al mondo: 105 metri di lunghezza, 27 colonne, capienza 25.000 persone — quando Danzica ne aveva 40.000 in tutto.",
                    url: "https://www.vivereinpolonia.pl/danzica-gdansk/", fonte: "Vivere in Polonia" }, tipo: "visita" },
        { ora: "~11:25", titolo: "Verso l'imbarco del galeone",
          dove: "Dlugie Pobrzeze 11, accanto al ristorante Gdanski Bowke - ~15 min a piedi",
          attenzione: "L'IMBARCO È CAMBIATO DAL 31 LUGLIO: NON È PIÙ ul. Wartka. Andare all'indirizzo vecchio significa arrivare al molo sbagliato con la corsa che parte. Essere al pontile per le 11:35: la regola è presentarsi 20-30 minuti prima, e siete in sei.",
          vai: "https://www.google.com/maps/dir/?api=1&destination=Dlugie%20Pobrzeze%2011%2C%20Gdansk%2C%20Poland&travelmode=walking", modo: "walking", tipo: "fisso" },
        { ora: "12:00", fisso: true, titolo: "Galeone 'Lew' > Westerplatte",
          dove: "Motlawa > Westerplatte - ~2h15 andata e ritorno",
          note: "Dove iniziò la Seconda guerra mondiale. Partenze ogni ora 10:00-19:00, ritorni da Westerplatte 11:30-19:30. I RITORNI SONO A CADENZA ORARIA: partendo alle 12:00 si sbarca alle 12:45 e il rientro utile è quello delle 13:30, cioè 45 MINUTI SUL SITO, non un'ora. Chi vuole più tempo prende il ritorno delle 14:30 e rientra alle 15:15, ma allora Sopot si accorcia. Andata e ritorno 100 zł intero / 75 ridotto (ridotto solo fino a 26 anni). Tutti seduti. Biglietti in cassa. Se le 12:00 sono piene si prende la corsa dopo, ma Sopot si accorcia.",
          storia: { testo: "Alle 4:48 del 1° settembre 1939 la corazzata tedesca Schleswig-Holstein aprì il fuoco su questa penisola: è l'istante in cui comincia la Seconda guerra mondiale. Meno di 200 soldati polacchi avevano l'ordine di resistere 12 ore. Resistettero sette giorni.",
                    url: "https://iviaggidibibi.it/viaggio-a-danzica-nei-luoghi-della-seconda-guerra-mondiale/", fonte: "I viaggi di Bibi" }, tipo: "spost" },
        { ora: "~14:15", titolo: "Pranzo leggero sul lungofiume", dove: "Danzica - ~60 min", tipo: "pasto" },
        { ora: "~15:20", titolo: "Verso la stazione + treno SKM per Sopot",
          dove: "Bolt/tram ~10 min + treno 26 min - ~5,20-6,50 zł",
          note: "I 26 minuti sono misurati DALLA STAZIONE, non dal lungofiume: vanno aggiunti ~10 min per raggiungerla (a piedi sarebbero 32). Treni ogni 7-10 minuti d'estate.",
          vai: "https://www.google.com/maps/dir/?api=1&destination=Molo%20w%20Sopocie%2C%20Sopot%2C%20Poland&travelmode=transit", modo: "transit", tipo: "spost" },
        { ora: "~16:00", titolo: "Sopot: il molo di legno più lungo d'Europa (511 m)",
          dove: "Sopot - ~2h30 a piedi",
          note: "Spiaggia, via Monte Cassino, bagno nel Baltico. Molo a pagamento in estate: 10 zł intero / 5 ridotto (dal 27/6 al 31/8, 24h su 24). Spiaggia e via Monte Cassino gratis. Molo piano in legno: comodo per tutti.",
          storia: { testo: "511 metri di legno sul Baltico: è il molo più lungo d'Europa. Sopot era la stazione balneare alla moda dell'Impero tedesco fra fine Ottocento e inizio Novecento — le ville liberty in giro per la città sono di allora.",
                    url: "https://poloniadavivere.it/cosa-vedere-a-sopot", fonte: "Polonia da Vivere" }, tipo: "visita" },
        { ora: "~18:30", titolo: "Rientro a Danzica", dove: "Treno + tram/Bolt - ~26 min",
          note: "18:30 e NON 19:00: altrimenti si arriva alla cena delle 20:00 direttamente dalla spiaggia, senza passare dall'hotel.",
          vai: "https://www.google.com/maps/dir/?api=1&destination=Hotel%20Sadova%2C%20Lakowa%2060%2C%2080-769%20Gdansk%2C%20Poland&travelmode=transit", modo: "transit", tipo: "spost" },
        { ora: "20:00", fisso: true, ok: true, titolo: "Cena di chiusura - Zafishowani - CONFERMATA",
          dove: "Tokarska 6, accanto al Zuraw - 15 min a piedi (1,1 km)",
          tel: "+48661511811",
          attenzione: "Il numero di telefono lasciato al locale è salvato SENZA il +39: se chiamano da un numero polacco quel numero non esiste. Si corregge dal link di riepilogo della prenotazione.",
          note: "Confermata dal locale l'1/8 alle 13:45. Aperto lunedì 13:00-23:00, cucina fino alle 22:30. Pesce e frutti di mare, fine-dining sul Motlawa: la cena-ricordo. ~26-36 euro a testa PIÙ il 12,5% di servizio automatico.",
          vai: "https://www.google.com/maps/dir/?api=1&destination=Zafishowani%2C%20Tokarska%206%2C%20Gdansk%2C%20Poland&travelmode=walking", modo: "walking", tipo: "pasto", mail: "https://app.notion.com/p/3b0bdffea7c781faa7e2fe1836fc9aee" },
        { ora: "~22:15", titolo: "Rientro a piedi", dove: "Sadova - ~15 min", note: "Ultima notte.",
          vai: "https://www.google.com/maps/dir/?api=1&destination=Hotel%20Sadova%2C%20Lakowa%2060%2C%2080-769%20Gdansk%2C%20Poland&travelmode=walking", modo: "walking", tipo: "spost" }
      ],
      pianoB: "Il galeone va comunque (c'è la coperta al chiuso), Sopot si accorcia. Alternativa al chiuso: Museo Marittimo sul Motlawa.",
      valvola: "La coda facoltativa Gdynia/Orlowo del vecchio piano si taglia: aggiungerebbe 1-1,5h senza necessità."
    },

    /* ---------------------------------------------------------------- G8 */
    {
      n: 8,
      meteo: { luogo: "Danzica", lat: 54.35, lon: 18.65 },
      data: "2026-08-11",
      etichetta: "Martedì 11 agosto",
      titolo: "Museo della II Guerra Mondiale > riconsegna auto > volo di sera",
      base: "volo",
      sveglia: "~8:15",
      carico: "pieno (le valigie stanno con voi tutto il giorno)",
      cappello: "Rifatta la sera del 10/8. La riconsegna RESTA alle 14:30 (deciso: niente telefonate a Europcar). Mattina al Museo della II Guerra Mondiale, che oggi è gratuito - con tutto quello che il gratis comporta. Le valigie stanno con voi tutto il giorno: a Danzica NON esiste deposito bagagli né in aeroporto né altrove sul percorso.",
      tappe: [
        { ora: "~8:15", titolo: "Sveglia, colazione veloce", dove: "Sadova - ~45 min",
          note: "Oggi non si dorme: il museo è gratuito e i biglietti si prendono SOLO in cassa il giorno stesso. Chi arriva tardi trova la fila, non il biglietto.", tipo: "riposo" },
        { ora: "~9:00", fisso: true, titolo: "Check-out e carico valigie nelle due auto",
          dove: "Sadova - ~15 min", tel: "+48583823030",
          attenzione: "Le valigie viaggiano con voi TUTTO il giorno. Niente deposito in hotel, niente armadietti in aeroporto: a GDN non esistono (verificato sull'elenco servizi ufficiale dello scalo).",
          note: "Il check-out formale è alle 11:00: uscire alle 9 è in anticipo, non un problema. Tassa di soggiorno 41,52 zł da saldare. Controllare cassaforte, bagno, prese e sotto i letti.", tipo: "riposo" },
        { ora: "~9:15", titolo: "Sadova > parcheggio sotterraneo del Museo",
          dove: "3,8 km in auto - 14 min (fino a 20 col traffico peggiore)",
          attenzione: "Ingresso del parcheggio da ul. WALOWA, non dal piazzale del museo. Altezza massima 1,90 m. Biglietto del parcheggio perso = 200 zł: uno per auto, in tasca a chi guida.",
          note: "142 posti su due livelli, apre alle 9:00. È chiuso e sorvegliato: è il posto migliore dove lasciare sei trolley per tre ore. Si paga alla macchinetta prima di uscire, SOLO CON CARTA: il martedì 30 minuti gratis, poi 10 zł per ogni ora iniziata (circa 40 zł a auto).",
          vai: "https://www.google.com/maps/dir/?api=1&destination=Muzeum%20II%20Wojny%20Swiatowej%2C%20plac%20Wladyslawa%20Bartoszewskiego%201%2C%2080-862%20Gdansk%2C%20Poland&travelmode=driving", waze: "https://waze.com/ul?ll=54.355866,18.659868&navigate=yes", modo: "driving", tipo: "spost" },
        { ora: "~9:35", fisso: true, titolo: "IN FILA ALLA CASSA - è il passaggio che decide la giornata",
          dove: "Museo della II Guerra Mondiale, plac Bartoszewskiego 1",
          tel: "+48587600960",
          attenzione: "Martedì l'ingresso è GRATUITO ma i biglietti si ritirano SOLO in cassa, il giorno stesso: il museo scrive nero su bianco che non accetta prenotazioni anticipate. Tetto di 2.500 visitatori. Casse aperte 9:30-14:30, museo 10:00-16:00.",
          note: "Qui si decide, non dopo: se la fila è lunga si molla e in 20 minuti si è a Westerplatte (RAMO B in fondo). Aspettare di vedere come va è il modo per perdere entrambe le cose.", tipo: "fisso" },
        { ora: "10:00", titolo: "Mostra principale", dove: "Museo - 3h10",
          note: "Il museo stesso dichiara TRE ORE come tempo minimo: il piano ve ne dà 3h10, non c'è margine per partire tardi. Audioguida 12 zł e c'è in ITALIANO - su una mostra di questa densità vale i soldi. È tutto sottoterra, fa fresco: bagno prima di scendere.",
          vai: "https://www.google.com/maps/dir/?api=1&destination=Muzeum%20II%20Wojny%20Swiatowej%2C%20plac%20Wladyslawa%20Bartoszewskiego%201%2C%2080-862%20Gdansk%2C%20Poland&travelmode=walking", modo: "walking", tipo: "visita" },
        { ora: "13:10", fisso: true, titolo: "USCITA OBBLIGATA - recupero auto e pagamento parcheggio",
          dove: "Parcheggio del museo - ~15 min",
          attenzione: "Non è un orario indicativo. Da qui all'Europcar sono 31 minuti normali ma 49 col traffico peggiore: uscendo alle 13:10 si arriva alle 14:15 anche nello scenario brutto. Oltre 30 minuti di ritardo sulla riconsegna, Europcar addebita un giorno intero a tariffa pubblica.", tipo: "fisso" },
        { ora: "~13:25", titolo: "Museo > Europcar aeroporto GDN",
          dove: "18,8 km in auto - 31 min (fino a 49 col traffico peggiore)",
          note: "Controllare sul contratto la politica carburante: se è pieno-pieno serve un distributore lungo la Slowackiego prima dell'aeroporto. Le due auto viaggiano in colonna: chi arriva primo si mette in fila all'ufficio.",
          vai: "https://www.google.com/maps/dir/?api=1&destination=Juliusza%20Slowackiego%20210A%2C%2080-298%20Gdansk%2C%20Poland&travelmode=driving", waze: "https://waze.com/ul?ll=54.382649,18.466261&navigate=yes", modo: "driving", tipo: "spost" },
        { ora: "14:30", fisso: true, titolo: "Riconsegna delle 2 auto",
          dove: "GDN, parcheggio 'P2 rent a car', Slowackiego 210A - ~30 min",
          tel: "+48665301685",
          note: "Ufficio presidiato 9:00-23:30: c'è l'addetto, ispezione sul posto, niente key-drop al buio. Farsi confermare lo sblocco del deposito di 300 euro sulla carta di Carlo. Poi 3 minuti a piedi fino al Terminal 2 (misurati).",
          vai: "https://www.google.com/maps/dir/?api=1&destination=Juliusza%20Slowackiego%20210A%2C%2080-298%20Gdansk%2C%20Poland&travelmode=driving", waze: "https://waze.com/ul?ll=54.382649,18.466261&navigate=yes", modo: "driving", tipo: "spost", mail: "https://app.notion.com/p/3b0bdffea7c781faa7e2fe1836fc9aee" },
        { ora: "~15:15", titolo: "Dentro il terminal e subito ai controlli",
          dove: "GDN Terminal 2, area Schengen",
          note: "Volo Schengen (nessun controllo passaporti) + check-in online già fatto + zero bagagli in stiva: si va dritti alla security, niente banco. Si passa presto proprio perché i trolley restano addosso: non c'è nessun posto dove lasciarli.", tipo: "spost" },
        { ora: "~15:45", titolo: "Riposo al Salon Executive",
          dove: "Area Schengen dopo i controlli - 150 zł a persona",
          tel: "+48583481199",
          note: "Aperto 5:00-21:00. Cibo e bevande inclusi, poltrone vere, bagni, wifi: è la scelta fatta per le due ore morte. Per sei persone circa 900 zł. Si compra online sul sito dell'aeroporto o direttamente all'ingresso della lounge.",
          attenzione: "Verificare all'ingresso se c'è un limite di permanenza: alcune fonti parlano di 3 ore. In quel caso si entra alle 15:50 e si esce all'imbarco.", tipo: "riposo" },
        { ora: "~18:45", titolo: "Imbarco", dove: "Gate sui monitor", tipo: "fisso" },
        { ora: "19:15", fisso: true, titolo: "Volo Wizz Air W6 1685 - Danzica > Catania",
          dove: "3h05 di volo, atterra alle 22:20",
          attenzione: "ETNA. Catania ieri ha chiuso agli arrivi per la TERZA volta in cinque giorni e viaggia a 5 atterraggi l'ora fino alle 6:00 di stamattina. Il volo può ritardare, saltare o essere dirottato su Palermo. Cosa fare in ciascuno dei tre casi: sezione REGOLE, voce ETNA.",
          note: "SOLO BAGAGLIO A MANO: 1 trolley 55x40x23 + 1 borsina 40x30x20 a testa, zero stiva. Regole diverse da Ryanair dell'andata.", tipo: "fisso", mail: "https://app.notion.com/p/3b0bdffea7c781faa7e2fe1836fc9aee" }
      ],
      pianoB: "RAMO B - WESTERPLATTE, si sceglie alle 9:35 guardando la fila. Dal museo sono 10,7 km, 19 minuti (26 col traffico peggiore). All'aperto, gratuito, nessuna coda, nessun tetto di visitatori: monumento ai Difensori della Costa, rovine delle caserme, Wartownia nr 1, cimitero. Ci siete già stati ieri col galeone, ma con 45 minuti scarsi a terra: stavolta si vede con calma e senza corsa al traghetto di ritorno. Si arriva alle 10:15, si riparte alle 13:00, all'Europcar per le 13:45 (44 minuti nel caso peggiore, la strada gira intorno al porto). Pranzo lungo la strada o in aeroporto. ATTENZIONE: a Westerplatte si parcheggia in SUPERFICIE, quindi niente valigie in vista - nel bagagliaio e coperte, prima di arrivare.",
      valvola: "Se al museo si entra tardi (dopo le 10:30) la mostra non ci sta in 3 ore: meglio vedere solo la prima metà con calma che correre. L'uscita alle 13:10 non si negozia, è l'unica cosa fissa della giornata insieme al volo."
    }
  ],

  /* ----------------------------------------------------------- PRIMA DI PARTIRE */
  primaDiPartire: {
    rosse: [
      { id: "carta-carlo", titolo: "La carta di credito di Carlo per l'auto",
        testo: "È il rosso più caro: senza, il 6/8 l'auto non si ritira e saltano i giorni dal 6 all'11. Al ritiro servono, TUTTI intestati a Carlo: patente + carta d'identità o passaporto (la patente da sola non basta) + la STESSA carta di credito con cui è stata pagata la prenotazione, su cui bloccano 300 euro di deposito. Aperto dal 26 luglio e mai verificato." },
      { id: "etna-volo-ritorno", titolo: "ETNA - controllare il volo di ritorno prima di uscire dall'hotel",
        testo: "Catania ha chiuso agli arrivi tre volte in cinque giorni e ieri sera viaggiava a 5 atterraggi l'ora. PRIMA di lasciare il Sadova: aprire l'app Wizz Air (sezione del volo W6 1685) e aeroporto.catania.it. Se il volo è già toccato, la giornata cambia e va rifatta - non si scopre alle 18:00 al gate. Cosa fare nei tre scenari: sezione REGOLE, voce ETNA." },
      { id: "novotel-dove", titolo: "Al Novotel non si sa dove presentarsi il 6/8",
        testo: "Il ritiro alle 9:00 è a un 'MPOINT' dentro l'hotel e non è pubblicato se sia alla reception o al garage. Con due taxi, sei persone e le valigie, cercarlo sul momento costa tempo. È la STESSA telefonata del punto qui sopra.",
        tel: "+48665301600" }
    ],
    online: [
      { id: "checkin-ryanair", titolo: "Check-in Ryanair - volo di andata", testo: "Si apre lunedì 3/8 alle 9:05 e chiude 2 ore prima del volo. Carte d'imbarco SOLO digitali: app installata e accesso già fatto." },
      { id: "checkin-wizz", titolo: "Check-in Wizz Air - volo di ritorno", testo: "Da provare subito: i posti 27A-27D risultano già assegnati, quindi la finestra dovrebbe essere aperta. Al banco costa 50 euro a persona. Vale per 4 persone: GLI ZII DEVONO FARE IL LORO." },
      { id: "checkin-ibis-zii", titolo: "Check-in online ibis DEGLI ZII", testo: "Quello di Raffaele è FATTO il 2/8 e vale per 2 camere / 4 adulti. Gli zii hanno una prenotazione separata e la finestra chiude alle 07:00 del 4/8, cioè mentre siete già in aeroporto. Da fare entro lunedì 3/8 sera. Verificare anche che sul codice di Raffaele risultino registrate ENTRAMBE le camere." },
    ],
    piccole: [
      { id: "colazione-roberts", titolo: "Colazione al Robert's Port sabato", testo: "Si parte alle 7:00 con 239 km davanti: se la colazione apre alle 8 serve un cestino. Telefonata mai fatta.", tel: "+48874298400" },
      { id: "parcheggio-sadova", titolo: "Parcheggio al Sadova", testo: "70 zł al giorno per auto, non prenotabile: 2 auto x 3 giorni = ~420 zł. Mai chiesto se c'è posto durante il Jarmark né qual è il ripiego.", tel: "+48583823030" },
      { id: "salon-executive", titolo: "Salon Executive di GDN per sei", testo: "Scelta del 10/8 per le due ore morte del pomeriggio: 150 zł a persona, circa 900 zł in sei. Si compra online sul sito dell'aeroporto (sezione passeggeri) o all'ingresso della lounge. Comprarlo online stasera evita di trovarlo pieno e di litigare con la carta al banco. Aperto 5:00-21:00, è DOPO i controlli.", tel: "+48583481199" },
      { id: "letti-sadova", titolo: "Letti al Sadova", testo: "È un monolocale per 4, non tre camere: Raffaele ed Emanuele condividono un matrimoniale. Verificare al check-in." },
      { id: "tel-zafishowani", titolo: "Telefono su Zafishowani", testo: "Salvato senza il +39: se il locale chiama da un numero polacco, quel numero non esiste. Si corregge dal link di riepilogo della prenotazione." },
      { id: "kayak-conferma", titolo: "Telefonare il kayak la sera prima", testo: "Giovedì sera va confermato l'appuntamento di venerdì mattina.", tel: "+48600029035" },
      { id: "mappe-offline", titolo: "Scaricare le mappe offline di Google Maps", testo: "AGGIUNTA DI OGGI, non era nei file del progetto. I percorsi qui dentro aprono l'app Google Maps, ma per navigare senza rete serve aver scaricato prima le aree: Varsavia, Masuria (Mikolajki), Danzica e la costa di Leba. In Google Maps: profilo > Mappe offline > Seleziona la tua mappa.", aggiunta: true }
    ]
  },

  /* ------------------------------------------------------------- PAROLE */
  /* Frasario che funziona SENZA RETE: e' il pezzo che serve davvero al
     ristorante o in cassa. La pronuncia e' scritta come si legge in italiano. */
  parole: [
    { g: "Le prime tre", voci: [
      { pl: "Dzień dobry", it: "Buongiorno", say: "gign DO-bri" },
      { pl: "Dziękuję", it: "Grazie", say: "gien-KU-ie" },
      { pl: "Proszę", it: "Per favore / prego", say: "PRO-scie" }
    ]},
    { g: "Al ristorante", voci: [
      { pl: "Stolik dla sześciu osób", it: "Un tavolo per sei", say: "STO-lik dla SCE-sciu O-sub" },
      { pl: "Poproszę menu", it: "Il menù, per favore", say: "po-PRO-scie MEnu" },
      { pl: "Czy jest menu po angielsku?", it: "C'è il menù in inglese?", say: "ci iest MEnu po an-GHIEL-sku" },
      { pl: "Rachunek, proszę", it: "Il conto, per favore", say: "ra-HU-nek PRO-scie" },
      { pl: "Czy mogę zapłacić kartą?", it: "Posso pagare con la carta?", say: "ci MO-ghe za-PUA-cic KAR-to" },
      { pl: "Bez cukru", it: "Senza zucchero", say: "bes TSU-kru" },
      { pl: "Woda niegazowana", it: "Acqua naturale", say: "VO-da nie-ga-zo-VA-na" },
      { pl: "Smacznego!", it: "Buon appetito!", say: "smacc-NE-go" }
    ]},
    { g: "In giro", voci: [
      { pl: "Gdzie jest toaleta?", it: "Dov'è il bagno?", say: "gdgie iest to-a-LE-ta" },
      { pl: "Ile to kosztuje?", it: "Quanto costa?", say: "I-le to kosc-TU-ie" },
      { pl: "Nie mówię po polsku", it: "Non parlo polacco", say: "gne MU-vie po POL-sku" },
      { pl: "Czy mówi pan/pani po angielsku?", it: "Parla inglese?", say: "ci MU-vi pan/PA-gni po an-GHIEL-sku" },
      { pl: "Przepraszam", it: "Scusi", say: "pscie-PRA-sciam" },
      { pl: "Sześć biletów, proszę", it: "Sei biglietti, per favore", say: "scescc bi-LE-tuv PRO-scie" },
      { pl: "Bilet ulgowy", it: "Biglietto ridotto", say: "BI-let ul-GO-vi" }
    ]},
    { g: "Se serve aiuto", voci: [
      { pl: "Pomocy!", it: "Aiuto!", say: "po-MO-tsi" },
      { pl: "Potrzebuję lekarza", it: "Ho bisogno di un medico", say: "po-tsce-BU-ie le-KA-gia" },
      { pl: "Apteka", it: "Farmacia", say: "ap-TE-ka" },
      { pl: "Zgubiłem się", it: "Mi sono perso", say: "zgu-BI-uem scie" }
    ]}
  ],

  /* ------------------------------------------------------------------ SOLDI */
  soldi: {
    riassunto: "Stima per il gruppo: 1.500-2.000 zł in contanti. Al bancomat SEMPRE in złoty, MAI in euro.",
    voci: [
      { q: "360 zł", t: "Kayak, venerdì mattina", d: "In CONTANTI, da avere prima di lasciare il resort: si paga sul posto prima della discesa." },
      { q: "~1.954 zł", t: "I quattro ingressi in cassa (~455 euro)", d: "Malbork 440 + Zoo 250 + Sea Park 714 + galeone 550. Carta accettata ovunque (in Polonia il POS c'è dappertutto), ma dev'esserci capienza." },
      { q: "~420 zł", t: "Parcheggio al Sadova", d: "70 zł al giorno per auto, 2 auto x 3 giorni. Non prenotabile." },
      { q: "41,52 zł", t: "Tassa di soggiorno a Danzica", d: "Al check-out." },
      { q: "~50-70 zł", t: "Melex alle dune, a testa", d: "Andata e ritorno. Il vecchio piano diceva 25-35: era solo andata." },
      { q: "94 zł", t: "Torre di Malbork per sei", d: "Biglietto a parte, 17 zł intero / 13 ridotto. Si sale 11:00-18:15." },
      { q: "15 zł", t: "Parcheggio alla Tana del Lupo", d: "Più 30 zł intero / 25 ridotto di ingresso." },
      { q: "10/5 zł", t: "Ingresso Parco Slowinski e molo di Sopot", d: "Intero / ridotto. Il molo è a pagamento dal 27/6 al 31/8, 24h su 24." },
      { q: "4,40 zł", t: "Biglietto mezzi a Varsavia", d: "Zona 1, vale 75 minuti." },
      { q: "85 zł", t: "Colazione al Sadova, a persona", d: "NON è inclusa nel soggiorno." }
    ],
    documenti: "In tasca, che in cassa li guardano davvero: la TESSERA UNIVERSITARIA di Raffaele (ridotto valido a Malbork, Zoo, galeone e Tana del Lupo - NON al Sea Park) e un DOCUMENTO DI EMANUELE, 16 anni."
  },

  /* ------------------------------------------------------------------ CASSA */
  cassa: {
    intro: "Castello di Malbork, Zoo di Varsavia, Sea Park delle foche e Galeone per Westerplatte: nessuno dei quattro si prenota online, si pagano sul posto il giorno stesso. Decisione di Raffaele del 31/07, non si riapre.",
    voci: [
      { g: "Mer 5/8", t: "Zoo di Varsavia", q: "250 zł", d: "Si risparmia la commissione di 4,50 zł. Nessuna fascia oraria. Conviene essere lì all'apertura delle 9:00, quando la fila è la più corta della giornata." },
      { g: "Sab 8/8", t: "Castello di Malbork", q: "440 zł", d: "Non c'è più uno slot da rincorrere: cade la pressione sulla partenza delle 7:00. La nuova variabile è la FILA ALLE CASSE di un sabato d'agosto. La lingua dell'audioguida si sceglieva comunque sul posto." },
      { g: "Dom 9/8", t: "Sea Park Sarbsk", q: "714 zł", d: "Parcheggio da 20 zł incluso nel totale. Sei biglietti allo sportello PRIMA dello spettacolo delle 16:00: partire da Leba alle 15:05, non 15:20." },
      { g: "Lun 10/8", t: "Galeone per Westerplatte", q: "550 zł", d: "Andata e ritorno. Partenze ogni ora dalle 10:00 alle 19:00: se le 12:00 sono piene si prende la corsa dopo, ma Sopot si accorcia. Presentarsi 20-30 minuti prima. ATTENZIONE AL MOLO: dal 31 luglio l'imbarco è a Dlugie Pobrzeze 11, accanto al Gdanski Bowke, NON più a ul. Wartka." }
    ]
  },

  /* --------------------------------------------------------------- TELEFONI */
  telefoni: [
    { gruppo: "Emergenze", voci: [
      { n: "Numero unico di emergenza", t: "112", nota: "Vale in tutta l'Unione Europea. Aggiunta di oggi.", aggiunta: true }
    ]},
    { gruppo: "Hotel", voci: [
      { n: "ibis Styles Warszawa City", t: "+48224883300", nota: "Varsavia, 4-6/8. Grzybowska 43." },
      { n: "Hotel Robert's Port", t: "+48874298400", nota: "Masuria, 6-8/8. Stare Sady 4, Mikolajki." },
      { n: "Robert's Port - ristorante", t: "+48875065400", nota: "Cena di giovedì." },
      { n: "Hotel Sadova - reception", t: "+48583823030", nota: "Danzica, 8-11/8. Lakowa 60. Anche per Papieroovka." }
    ]},
    { gruppo: "Auto", voci: [
      { n: "Europcar MPOINT Novotel (Varsavia)", t: "+48665301600", nota: "Ritiro del 6/8: chiedere DOVE ci si presenta." },
      { n: "Europcar aeroporto GDN", t: "+48665301685", nota: "Riconsegna dell'11/8 alle 14:30, CONFERMATA così: non si sposta più. Ufficio presidiato 9:00-23:30." }
    ]},
    { gruppo: "Ultimo giorno (11/8)", voci: [
      { n: "Museo della II Guerra Mondiale", t: "+48587600960", nota: "Martedì: casse 9:30-14:30, museo 10:00-16:00, ingresso gratuito ma biglietti solo in cassa.", aggiunta: true },
      { n: "Salon Executive aeroporto GDN", t: "+48583481199", nota: "La lounge dove riposate il pomeriggio. 150 zł a persona, 5:00-21:00, dopo i controlli.", aggiunta: true }
    ]},
    { gruppo: "Attività", voci: [
      { n: "Kayak Sakowscy / Wan Plac", t: "+48600029035", nota: "Venerdì mattina. Un dipendente parla italiano." },
      { n: "Melex alle dune di Leba", t: "+48886354555", nota: "Navetta elettrica, domenica." },
      { n: "Zoo di Varsavia", t: "+48226194041", nota: "Solo se si vuole l'interno della Villa Zabinski." }
    ]},
    { gruppo: "Ristoranti - confermati", voci: [
      { n: "Beef & Pepper (mer 5/8)", t: "+48785025025", nota: "Confermato. Nessun codice: nome + data + ora." },
      { n: "Kubicki (sab 8/8)", t: "+48583010050", nota: "Confermato dal locale l'1/8." },
      { n: "Zafishowani (lun 10/8)", t: "+48661511811", nota: "Confermato l'1/8 alle 13:45." }
    ]},
    { gruppo: "Ristoranti - da confermare", voci: [
      { n: "Podwale 25 (mar 4/8)", t: "+48226356314", nota: "Nessuna conferma arrivata: verificare l'SMS." },
      { n: "Spizarnia Mazury (ven 7/8)", t: "+48451101330", nota: "Silenzio dal 1/8. Altro numero: +48 509 188 057." },
      { n: "w Zatoce (ven 7/8, alternativa)", t: "+48874219000", nota: "È un hotel: la reception risponde sempre. Chiude alle 21:00 il venerdì." },
      { n: "Bistro na Fali (pranzo sab 8/8)", t: "+48534610670", nota: "Silenzio dal 1/8. Aperto da mezzogiorno tutti i giorni." },
      { n: "True (dom 9/8) - WhatsApp", t: "+48727600601", nota: "Silenzio dal 1/8." }
    ]},
    { gruppo: "Alternative già valutate", voci: [
      { n: "Gvara (Danzica)", t: "+48795889288", nota: "4,6 su 3.562 recensioni." },
      { n: "Brovarnia (Danzica)", t: "+48726030400", nota: "Birreria storica." },
      { n: "Symfonia Smaku (Varsavia)", t: "+48225584524", nota: "5 min a piedi dall'ibis. Chiamare per gli orari." },
      { n: "Nova Wola (Varsavia)", t: "+48223773801", nota: "12 min a piedi. Cena 17:00-22:30 confermata." }
    ]}
  ],

  /* ----------------------------------------------------------- PRENOTAZIONI */
  prenotazioni: {
    avviso: "I CODICI DI PRENOTAZIONE NON SONO QUI. Stanno solo nel PDF sul telefono, per non metterli su un indirizzo pubblico. Qui ci sono orari, indirizzi e condizioni.",
    voci: [
      { tipo: "Volo andata", t: "Ryanair FR5441", d: "Mar 4/8, Catania 09:05 > Varsavia Modlin 11:50. Posti 29A-29D. Priorità + 2 bagagli a mano, zero stiva. Carte d'imbarco solo digitali." },
      { tipo: "Volo ritorno", t: "Wizz Air W6 1685", d: "Mar 11/8, Danzica 19:15 > Catania 22:20. Posti 27A-27D. SOLO bagaglio a mano: 1 trolley 55x40x23 + 1 borsina 40x30x20 a testa." },
      { tipo: "Transfer", t: "Welcome Pickups, 75 euro", d: "Mar 4/8 da Modlin all'ibis. Minivan da 8 posti (non da 4). L'autista monitora il volo. Cercare l'hotel per indirizzo Grzybowska 43, mai per nome." },
      { tipo: "Hotel 1", t: "ibis Styles Warszawa City", d: "Grzybowska 43, Varsavia. 4-6/8, 2 camere per 4 adulti. Camera dalle 15:00, rilascio entro le 11:00. Zero da saldare: prepagato, colazione e WiFi inclusi. Tariffa NON rimborsabile. Check-in online fatto il 2/8." },
      { tipo: "Auto", t: "Europcar - Renault Clio", d: "Ritiro giovedì 6/8 ore 9:00 all'MPOINT del Novotel Centrum, Marszalkowska 94/98. Prepagata. Secondo guidatore e Premium Protection inclusi. Deposito di 300 euro bloccato sulla carta. Riconsegna martedì 11/8 ore 14:30 all'aeroporto GDN, Slowackiego 210A, parcheggio 'P2 rent a car' - orario CONFERMATO il 10/8, lo spostamento alle 16:00 è stato scartato." },
      { tipo: "Hotel 2", t: "Hotel Robert's Port", d: "Stare Sady 4, Mikolajki. 6-8/8, Domek Zeglarza, già pagato, intestato a Carlo. Lake resort & spa: piscina coperta, jacuzzi, sauna, hammam, spiaggia sul lago inclusi. Ristorante aperto 12:00-22:00. Parcheggio in superficie sul posto." },
      { tipo: "Hotel 3", t: "Hotel Sadova", d: "Lakowa 60, Danzica. 8-11/8, già pagato, non rimborsabile, intestato a Raffaele. È un MONOLOCALE PER 4. Colazione esclusa (85 zł a persona). Tassa di soggiorno 41,52 zł in loco. Parcheggio 70 zł al giorno per auto, non prenotabile." },
      { tipo: "Cene confermate", t: "Beef & Pepper, Kubicki, Zafishowani", d: "Mer 5/8 ore 20:00 sala INSIDE - Sab 8/8 ore 19:30 - Lun 10/8 ore 20:00. Tutte per 6 persone." },
      { tipo: "Cene da confermare", t: "Podwale 25, Spizarnia/w Zatoce, Bistro na Fali, True", d: "Mar 4/8 20:30 - Ven 7/8 19:30 (o 19:00 se vince w Zatoce) - Sab 8/8 pranzo 14:15 - Dom 9/8 20:00." },
      { tipo: "Regola ferma", t: "Le prenotazioni di Raffaele coprono 4 persone, MAI gli zii", d: "Accertato il 2/8 su due casi indipendenti (volo Wizz = 4 passeggeri, hotel ibis = 2 camere / 4 adulti). Gli zii viaggiano su codici propri e devono fare da soli i loro check-in. Davanti a qualunque prenotazione, prima di darla per buona: per quante persone vale?" }
    ]
  },

  /* -------------------------------------------------------------- REGOLE */
  regole: [
    { t: "ETNA - i tre scenari del ritorno", d: "SITUAZIONE (10/8 sera): l'Etna erutta dal cratere Voragine con cenere verso Sud-Sud-Ovest. Catania ha sospeso gli arrivi tre volte in cinque giorni; ieri ha riaperto alle 16:15 ma con un tetto di 5 atterraggi l'ora fino alle 6:00 di oggi, per chiusura del settore di volo B2. L'aeroporto di dirottamento è PALERMO; in questi giorni sono stati attivati bus e treni straordinari da Palermo, Trapani e Comiso verso Catania. -- SCENARIO 1, il volo salta o slitta mentre siete ancora a Danzica: l'eruzione è 'circostanza eccezionale' secondo il regolamento europeo 261/2004, quindi NON spetta la compensazione in denaro (i 250-400 euro), MA restano interamente dovute la RIPROTEZIONE sul primo volo utile e l'ASSISTENZA (pasti, e se si dorme lì, hotel e trasporti). Si chiede alla compagnia prima di muoversi da soli; se la compagnia non provvede, si provvede e si chiede il rimborso dopo, con TUTTE le ricevute. -- SCENARIO 2, il volo parte ma atterra a Palermo: la compagnia è tenuta a garantire, o a rimborsare per intero, il trasporto fino a Catania. Non allontanarsi dagli arrivi prima di aver capito dove si prende il bus: sono circa 200 km, 2 ore e mezza-3 di strada. Se non organizza nessuno, ci si muove da soli e si conserva ogni scontrino. -- SCENARIO 3, si atterra a Catania ma in ritardo: l'unico problema è chi viene a prendervi. Si avvisa in tempo reale, non all'atterraggio." },
    { t: "ETNA - cosa preparare stasera", d: "Carte d'imbarco anche in SCREENSHOT, non solo dentro l'app: se il volo cambia, l'app si affolla e la rete pure. Powerbank carico e in bagaglio a mano (in stiva non si può, e comunque stiva non ne avete). Un po' di CONTANTI in euro per un bus o un taxi in Sicilia, che a mezzanotte con una carta straniera si perde tempo. Avvisare adesso chi vi viene a prendere a Catania che l'orario è incerto. E non comprare all'ultimo cose che rendono i trolley ingestibili: se finite a Palermo, quel bagaglio ve lo portate per altre tre ore." },
    { t: "Il cuscinetto", d: "Tra due cose a orario si conta: uscire dall'attività precedente + raggiungere il mezzo + spostamento NEL CASO PEGGIORE + parcheggio e ultimo tratto a piedi. POI il margine: minimo 30 minuti, 45 se in mezzo c'è una barca, un volo o un treno. Mai zero. Se non ci sta, si sposta l'orario, non si stringe il margine." },
    { t: "Manda solo Raffaele", d: "Carlo e Giovanna non inviano più nulla: nessun rischio di doppio tavolo." },
    { t: "Prima di dire che un fornitore non risponde", d: "Controllare (a) che la mail sia stata CONSEGNATA - un avviso di mancata consegna arriva anche 30 ore dopo - e (b) la cartella spam. Con Rejsjachtem la mail era morta e WhatsApp funzionava." },
    { t: "Le prenotazioni coprono 4 persone", d: "Mai gli zii. Loro hanno codici propri e fanno da soli i loro check-in." }
  ]
};
